from django.conf.urls.defaults import *

urlpatterns = patterns('refs.rules.views',
    url(r'^$', 'index', name='root'),
#    url(r'^websites/$', 'view_websites', name='view_websites' ),
    url(r'^website/(?P<id>\d+)/$', 'view_website', name='view_website' ),
    url(r'^websites/add/$', 'add_edit_website', name='add_website' ),
    url(r'^website/(?P<id>\d+)/edit/$', 'add_edit_website', name='edit_website' ),
    url(r'^website/(?P<website_id>\d+)/profiles/$', 'filters', name='filters' ),
    url(r'^website/(?P<website_id>\d+)/profile/add/$', 'add_edit_filter', name='add_filter' ),
    url(r'^website/(?P<website_id>\d+)/profile/check/$', 'check_filter', name='check_filter' ),
    url(r'^website/(?P<website_id>\d+)/profile/preview/$', 'preview_filter', name='preview_filter' ),
    url(r'^website/(?P<website_id>\d+)/profile/(?P<filter_id>\d+)/edit/$', 'add_edit_filter', name='edit_filter' ),
    url(r'^website/(?P<website_id>\d+)/profile/(?P<filter_id>\d+)/delete/$', 'delete_filter', name='delete_filter' ),
    url(r'^website/(?P<website_id>\d+)/profile/(?P<filter_id>\d+)/de_activate/(?P<activate>[01])/$', 'de_activate_filter', name='de_activate_filter' ),
    url(r'^website/(?P<website_id>\d+)/rule/add/$', 'add_edit_rule', name='add_rule' ),
    url(r'^website/(?P<website_id>\d+)/rule/(?P<rule_id>\d+)/edit/$', 'add_edit_rule', name='edit_rule' ),
    url(r'^website/(?P<website_id>\d+)/rule/(?P<rule_id>\d+)/copy/(?P<copy>[01])/$', 'add_edit_rule', name='copy_rule' ),
    url(r'^website/(?P<website_id>\d+)/rule/(?P<rule_id>\d+)/delete/$', 'delete_rule', name='delete_rule' ),
    url(r'^website/(?P<website_id>\d+)/rules/$', 'rules', name='rules' ),
    url(r'^website/(?P<website_id>\d+)/admin/$', 'administer_site', name='administer_site' ),
    url(r'^website/(?P<website_id>\d+)/admin/invite/(?P<invite_id>\d+)/delete/$', 'delete_user_or_invite', name='delete_invite' ),
    url(r'^website/(?P<website_id>\d+)/admin/user/(?P<wuser_id>\d+)/delete/$', 'delete_user_or_invite', name='delete_user' ),
    url(r'^website/(?P<website_id>\d+)/verify/$', 'verify_website', name='verify_website' ),
)
